<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.eclipse</groupId>
		<artifactId>marketplacepki</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>

	<artifactId>eclipse.core.pki.tests</artifactId>
	<packaging>pom</packaging>
	<properties>
		<code.ignoredWarnings>${tests.ignoredWarnings}</code.ignoredWarnings>
	</properties>
	<modules>

		<module>org.eclipse.core.tests.pki</module>

	</modules>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-core</artifactId>
				<version>5.15.2</version> <!-- Specify the latest version here -->
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.powermock</groupId>
				<artifactId>powermock-core</artifactId>
				<version>2.0.9</version>
				<scope>test</scope>
			</dependency>

			<dependency>
				<groupId>org.powermock</groupId>
				<artifactId>powermock-mockito-release-full</artifactId>
				<version>1.6.4</version>
				<type>pom</type>
				<scope>test</scope>
			</dependency>

		</dependencies>
	</dependencyManagement>
</project>

